package com.networktoolbox.feature.report.presentation

import android.content.Context
import com.networktoolbox.core.common.diagnostic.DiagnosticText
import com.networktoolbox.core.common.diagnostic.DiagnosticTextArgument
import com.networktoolbox.feature.report.R
import java.util.Locale

/**
 * Immutable resource snapshot. Capture once at the UI/export boundary; no
 * formatter line reads a mutable system or application locale.
 */
class ReportLocalizationContext private constructor(
    val locale: Locale,
    private val templates: Map<String, String>,
) {
    /** A resource-backed presentation template, never a legacy-text lookup. */
    internal fun text(code: String, fallback: String, vararg arguments: Any): String = render(
        DiagnosticText(code, runCatching { String.format(locale, fallback, *arguments) }.getOrDefault(fallback), arguments.map {
            when (it) {
                is Int -> DiagnosticTextArgument.Integer(it.toLong())
                is Long -> DiagnosticTextArgument.Integer(it)
                is Double -> DiagnosticTextArgument.Decimal(it)
                is Float -> DiagnosticTextArgument.Decimal(it.toDouble())
                is String -> DiagnosticTextArgument.Text(it)
                else -> error("Unsupported presentation argument")
            }
        }),
        fallback,
    )

    fun render(message: DiagnosticText?, fallback: String): String {
        if (message == null) return fallback
        val safeFallback = message.fallbackText.takeIf(String::isNotBlank) ?: fallback
        val template = templates[message.code] ?: return safeFallback
        val arguments = message.arguments.map<DiagnosticTextArgument, Any> {
            when (it) {
                is DiagnosticTextArgument.Text -> it.value
                is DiagnosticTextArgument.Integer -> it.value
                is DiagnosticTextArgument.Decimal -> it.value
            }
        }.toTypedArray()
        return runCatching {
            // Do not silently drop extra arguments on an incompatible future message.
            val slots = Regex("%(?:(\\d+)\\$)?(?:\\.\\d+)?[sdf]").findAll(template).toList()
            require(slots.size == arguments.size)
            String.format(locale, template, *arguments)
        }.getOrDefault(safeFallback)
    }

    companion object {
        fun capture(context: Context): ReportLocalizationContext {
            val resources = context.resources
            val locale = resources.configuration.locales[0] ?: Locale.ENGLISH
            // Strings, not a Context/Resources reference, cross the export boundary.
            return ReportLocalizationContext(locale, resourceIds.mapValues { resources.getString(it.value) })
        }

        /** No message inference for a legacy caller or legacy prose. */
        fun legacy() = ReportLocalizationContext(Locale.SIMPLIFIED_CHINESE, emptyMap())

        internal fun fromTemplates(locale: Locale, templates: Map<String, String>) =
            ReportLocalizationContext(locale, templates.toMap())

        private val resourceIds = mapOf(
            "check_detail_skip_ip_no_network" to R.string.check_detail_skip_ip_no_network,
            "check_detail_skip_gateway_no_network" to R.string.check_detail_skip_gateway_no_network,
            "check_detail_skip_public_no_network" to R.string.check_detail_skip_public_no_network,
            "check_detail_skip_dns_no_network" to R.string.check_detail_skip_dns_no_network,
            "check_detail_skip_target_no_network" to R.string.check_detail_skip_target_no_network,
            "check_detail_network_read_failed" to R.string.check_detail_network_read_failed,
            "check_detail_network_unconfirmed" to R.string.check_detail_network_unconfirmed,
            "check_detail_network_active" to R.string.check_detail_network_active,
            "check_detail_network_absent" to R.string.check_detail_network_absent,
            "check_detail_ip_observed" to R.string.check_detail_ip_observed,
            "check_detail_ip_unconfirmed" to R.string.check_detail_ip_unconfirmed,
            "check_detail_gateway_mobile" to R.string.check_detail_gateway_mobile,
            "check_detail_gateway_missing" to R.string.check_detail_gateway_missing,
            "check_detail_gateway_scope_missing" to R.string.check_detail_gateway_scope_missing,
            "check_detail_gateway_incomplete" to R.string.check_detail_gateway_incomplete,
            "check_detail_gateway_responded" to R.string.check_detail_gateway_responded,
            "check_detail_gateway_no_response" to R.string.check_detail_gateway_no_response,
            "check_detail_public_targets_missing" to R.string.check_detail_public_targets_missing,
            "check_detail_public_tcp_outcome" to R.string.check_detail_public_tcp_outcome,
            "check_detail_target_unselected" to R.string.check_detail_target_unselected,
            "check_detail_target_no_address" to R.string.check_detail_target_no_address,
            "check_detail_target_tcp_outcome" to R.string.check_detail_target_tcp_outcome,
            "check_detail_dns_unconfirmed" to R.string.check_detail_dns_unconfirmed,
            "check_detail_dns_outcome" to R.string.check_detail_dns_outcome,
            "check_detail_network_changed" to R.string.check_detail_network_changed,
            "verification_runs_incomplete" to R.string.verification_runs_incomplete,
            "verification_target_changed" to R.string.verification_target_changed,
            "verification_target_missing" to R.string.verification_target_missing,
            "verification_fingerprint_missing" to R.string.verification_fingerprint_missing,
            "verification_network_changed" to R.string.verification_network_changed,
            "verification_no_network_resolved" to R.string.verification_no_network_resolved,
            "verification_no_network_persistent" to R.string.verification_no_network_persistent,
            "verification_resolved" to R.string.verification_resolved,
            "verification_persistent" to R.string.verification_persistent,
            "verification_new_findings" to R.string.verification_new_findings,
            "verification_unchanged" to R.string.verification_unchanged,
            "verification_inconclusive" to R.string.verification_inconclusive,
            "verification_context_changed" to R.string.verification_context_changed,
            "report_dynamic_document_title" to R.string.report_dynamic_document_title,
            "report_dynamic_section_metadata" to R.string.report_dynamic_section_metadata,
            "report_dynamic_section_conclusion" to R.string.report_dynamic_section_conclusion,
            "report_dynamic_section_checks" to R.string.report_dynamic_section_checks,
            "report_dynamic_section_findings" to R.string.report_dynamic_section_findings,
            "report_dynamic_section_recommendations" to R.string.report_dynamic_section_recommendations,
            "report_dynamic_section_network" to R.string.report_dynamic_section_network,
            "report_dynamic_section_details" to R.string.report_dynamic_section_details,
            "report_dynamic_section_evidence" to R.string.report_dynamic_section_evidence,
            "report_dynamic_section_privacy" to R.string.report_dynamic_section_privacy,
            "report_dynamic_field_timestamp" to R.string.report_dynamic_field_timestamp,
            "report_dynamic_field_status" to R.string.report_dynamic_field_status,
            "report_dynamic_field_severity" to R.string.report_dynamic_field_severity,
            "report_dynamic_field_summary" to R.string.report_dynamic_field_summary,
            "report_dynamic_field_type" to R.string.report_dynamic_field_type,
            "report_dynamic_field_address" to R.string.report_dynamic_field_address,
            "report_dynamic_field_prefix" to R.string.report_dynamic_field_prefix,
            "report_dynamic_field_gateway" to R.string.report_dynamic_field_gateway,
            "report_dynamic_field_next_hop" to R.string.report_dynamic_field_next_hop,
            "report_dynamic_field_dns" to R.string.report_dynamic_field_dns,
            "report_dynamic_field_private_dns" to R.string.report_dynamic_field_private_dns,
            "report_dynamic_field_private_dns_name" to R.string.report_dynamic_field_private_dns_name,
            "report_dynamic_field_validated" to R.string.report_dynamic_field_validated,
            "report_dynamic_field_target" to R.string.report_dynamic_field_target,
            "report_dynamic_field_method" to R.string.report_dynamic_field_method,
            "report_dynamic_field_description" to R.string.report_dynamic_field_description,
            "report_dynamic_field_evidence" to R.string.report_dynamic_field_evidence,
            "report_dynamic_field_active" to R.string.report_dynamic_field_active,
            "report_dynamic_field_captive" to R.string.report_dynamic_field_captive,
            "report_dynamic_field_partial" to R.string.report_dynamic_field_partial,
            "report_dynamic_field_interface" to R.string.report_dynamic_field_interface,
            "report_dynamic_field_latency" to R.string.report_dynamic_field_latency,
            "report_dynamic_field_tcp" to R.string.report_dynamic_field_tcp,
            "report_dynamic_field_dns_outcome" to R.string.report_dynamic_field_dns_outcome,
            "report_dynamic_field_dns_record" to R.string.report_dynamic_field_dns_record,
            "report_dynamic_field_priority" to R.string.report_dynamic_field_priority,
            "report_dynamic_field_network_change" to R.string.report_dynamic_field_network_change,
            "report_dynamic_unknown" to R.string.report_dynamic_unknown,
            "report_dynamic_not_provided" to R.string.report_dynamic_not_provided,
            "report_dynamic_not_configured" to R.string.report_dynamic_not_configured,
            "report_dynamic_not_detected" to R.string.report_dynamic_not_detected,
            "report_dynamic_enabled" to R.string.report_dynamic_enabled,
            "report_dynamic_disabled" to R.string.report_dynamic_disabled,
            "report_dynamic_confirmed" to R.string.report_dynamic_confirmed,
            "report_dynamic_unconfirmed" to R.string.report_dynamic_unconfirmed,
            "report_dynamic_validation_passed" to R.string.report_dynamic_validation_passed,
            "report_dynamic_validation_not_passed" to R.string.report_dynamic_validation_not_passed,
            "report_dynamic_empty_network" to R.string.report_dynamic_empty_network,
            "report_dynamic_no_clear_fault" to R.string.report_dynamic_no_clear_fault,
            "report_dynamic_privacy_details" to R.string.report_dynamic_privacy_details,
            "report_dynamic_privacy_local" to R.string.report_dynamic_privacy_local,
            "report_dynamic_severity_healthy" to R.string.report_dynamic_severity_healthy,
            "report_dynamic_severity_notice" to R.string.report_dynamic_severity_notice,
            "report_dynamic_severity_warning" to R.string.report_dynamic_severity_warning,
            "report_dynamic_severity_error" to R.string.report_dynamic_severity_error,
            "report_dynamic_diagnosis_normal" to R.string.report_dynamic_diagnosis_normal,
            "report_dynamic_diagnosis_attention" to R.string.report_dynamic_diagnosis_attention,
            "report_dynamic_diagnosis_limited" to R.string.report_dynamic_diagnosis_limited,
            "report_dynamic_diagnosis_unknown" to R.string.report_dynamic_diagnosis_unknown,
            "report_dynamic_stage_network_state" to R.string.report_dynamic_stage_network_state,
            "report_dynamic_stage_ip_configuration" to R.string.report_dynamic_stage_ip_configuration,
            "report_dynamic_stage_gateway" to R.string.report_dynamic_stage_gateway,
            "report_dynamic_stage_internet" to R.string.report_dynamic_stage_internet,
            "report_dynamic_stage_dns" to R.string.report_dynamic_stage_dns,
            "report_dynamic_stage_target" to R.string.report_dynamic_stage_target,
            "report_dynamic_stage_advanced_path" to R.string.report_dynamic_stage_advanced_path,
            "report_dynamic_check_pass" to R.string.report_dynamic_check_pass,
            "report_dynamic_check_fail" to R.string.report_dynamic_check_fail,
            "report_dynamic_check_no_records" to R.string.report_dynamic_check_no_records,
            "report_dynamic_check_not_applicable" to R.string.report_dynamic_check_not_applicable,
            "report_dynamic_check_skipped" to R.string.report_dynamic_check_skipped,
            "report_dynamic_check_unknown" to R.string.report_dynamic_check_unknown,
            "report_dynamic_confidence_high" to R.string.report_dynamic_confidence_high,
            "report_dynamic_confidence_medium" to R.string.report_dynamic_confidence_medium,
            "report_dynamic_confidence_low" to R.string.report_dynamic_confidence_low,
            "report_dynamic_evidence_confirmed" to R.string.report_dynamic_evidence_confirmed,
            "report_dynamic_evidence_supported" to R.string.report_dynamic_evidence_supported,
            "report_dynamic_evidence_inconclusive" to R.string.report_dynamic_evidence_inconclusive,
            "report_dynamic_evidence_contradicted" to R.string.report_dynamic_evidence_contradicted,
            "report_dynamic_connection_wifi" to R.string.report_dynamic_connection_wifi,
            "report_dynamic_connection_cellular" to R.string.report_dynamic_connection_cellular,
            "report_dynamic_connection_ethernet" to R.string.report_dynamic_connection_ethernet,
            "report_dynamic_connection_vpn" to R.string.report_dynamic_connection_vpn,
            "report_dynamic_connection_bluetooth" to R.string.report_dynamic_connection_bluetooth,
            "report_dynamic_connection_unknown" to R.string.report_dynamic_connection_unknown,
            "report_dynamic_tcp_connect_success" to R.string.report_dynamic_tcp_connect_success,
            "report_dynamic_tcp_connection_refused" to R.string.report_dynamic_tcp_connection_refused,
            "report_dynamic_tcp_timeout" to R.string.report_dynamic_tcp_timeout,
            "report_dynamic_tcp_network_unreachable" to R.string.report_dynamic_tcp_network_unreachable,
            "report_dynamic_tcp_no_route" to R.string.report_dynamic_tcp_no_route,
            "report_dynamic_tcp_unknown" to R.string.report_dynamic_tcp_unknown,
            "report_dynamic_tcp_internal_error" to R.string.report_dynamic_tcp_internal_error,
            "report_dynamic_dns_success" to R.string.report_dynamic_dns_success,
            "report_dynamic_dns_partial" to R.string.report_dynamic_dns_partial,
            "report_dynamic_dns_no_records" to R.string.report_dynamic_dns_no_records,
            "report_dynamic_dns_nxdomain" to R.string.report_dynamic_dns_nxdomain,
            "report_dynamic_dns_timeout" to R.string.report_dynamic_dns_timeout,
            "report_dynamic_dns_network_error" to R.string.report_dynamic_dns_network_error,
            "report_dynamic_dns_invalid_response" to R.string.report_dynamic_dns_invalid_response,
            "report_dynamic_dns_unknown" to R.string.report_dynamic_dns_unknown,
            "report_dynamic_method_system_reachability" to R.string.report_dynamic_method_system_reachability,
            "report_dynamic_method_icmp" to R.string.report_dynamic_method_icmp,
            "report_dynamic_method_unavailable" to R.string.report_dynamic_method_unavailable,
            "report_dynamic_method_tcp_connect" to R.string.report_dynamic_method_tcp_connect,
            "report_dynamic_method_system_dns" to R.string.report_dynamic_method_system_dns,
            "report_dynamic_method_system_resolver" to R.string.report_dynamic_method_system_resolver,
            "report_dynamic_method_android_dns_resolver" to R.string.report_dynamic_method_android_dns_resolver,
            "report_dynamic_method_tcp_443_probes_with_validated_context" to R.string.report_dynamic_method_tcp_443_probes_with_validated_context,
            "report_dynamic_method_tcp_connect_to_resolved_address" to R.string.report_dynamic_method_tcp_connect_to_resolved_address,
            "report_dynamic_method_other" to R.string.report_dynamic_method_other,
            "report_dynamic_public_all" to R.string.report_dynamic_public_all,
            "report_dynamic_public_some" to R.string.report_dynamic_public_some,
            "report_dynamic_public_unknown" to R.string.report_dynamic_public_unknown,
            "report_dynamic_public_no_success" to R.string.report_dynamic_public_no_success,
            "report_dynamic_stage_different" to R.string.report_dynamic_stage_different,
            "report_dynamic_stage_some_different" to R.string.report_dynamic_stage_some_different,
            "check_network_state_pass" to R.string.check_network_state_pass,
            "check_network_state_fail" to R.string.check_network_state_fail,
            "check_network_state_unknown" to R.string.check_network_state_unknown,
            "check_network_state_not_applicable" to R.string.check_network_state_not_applicable,
            "check_network_state_skipped" to R.string.check_network_state_skipped,
            "check_network_state_no_records" to R.string.check_network_state_no_records,
            "check_ip_configuration_pass" to R.string.check_ip_configuration_pass,
            "check_ip_configuration_fail" to R.string.check_ip_configuration_fail,
            "check_ip_configuration_unknown" to R.string.check_ip_configuration_unknown,
            "check_ip_configuration_not_applicable" to R.string.check_ip_configuration_not_applicable,
            "check_ip_configuration_skipped" to R.string.check_ip_configuration_skipped,
            "check_ip_configuration_no_records" to R.string.check_ip_configuration_no_records,
            "check_gateway_pass" to R.string.check_gateway_pass,
            "check_gateway_fail" to R.string.check_gateway_fail,
            "check_gateway_unknown" to R.string.check_gateway_unknown,
            "check_gateway_not_applicable" to R.string.check_gateway_not_applicable,
            "check_gateway_skipped" to R.string.check_gateway_skipped,
            "check_gateway_no_records" to R.string.check_gateway_no_records,
            "check_internet_pass" to R.string.check_internet_pass,
            "check_internet_fail" to R.string.check_internet_fail,
            "check_internet_unknown" to R.string.check_internet_unknown,
            "check_internet_not_applicable" to R.string.check_internet_not_applicable,
            "check_internet_skipped" to R.string.check_internet_skipped,
            "check_internet_no_records" to R.string.check_internet_no_records,
            "check_dns_pass" to R.string.check_dns_pass,
            "check_dns_fail" to R.string.check_dns_fail,
            "check_dns_unknown" to R.string.check_dns_unknown,
            "check_dns_not_applicable" to R.string.check_dns_not_applicable,
            "check_dns_skipped" to R.string.check_dns_skipped,
            "check_dns_no_records" to R.string.check_dns_no_records,
            "check_target_pass" to R.string.check_target_pass,
            "check_target_fail" to R.string.check_target_fail,
            "check_target_unknown" to R.string.check_target_unknown,
            "check_target_not_applicable" to R.string.check_target_not_applicable,
            "check_target_skipped" to R.string.check_target_skipped,
            "check_target_no_records" to R.string.check_target_no_records,
            "check_advanced_path" to R.string.check_advanced_path,
            "recommendation_retry_title" to R.string.recommendation_retry_title,
            "recommendation_retry_stable_action" to R.string.recommendation_retry_stable_action,
            "recommendation_network_changed_reason" to R.string.recommendation_network_changed_reason,
            "diagnosis_network_changed_title" to R.string.diagnosis_network_changed_title,
            "diagnosis_network_changed_explanation" to R.string.diagnosis_network_changed_explanation,
            "diagnosis_incomplete_title" to R.string.diagnosis_incomplete_title,
            "diagnosis_incomplete_explanation" to R.string.diagnosis_incomplete_explanation,
            "recommendation_retry_later_action" to R.string.recommendation_retry_later_action,
            "recommendation_incomplete_reason" to R.string.recommendation_incomplete_reason,
            "finding_no_network_title" to R.string.finding_no_network_title,
            "finding_no_network_description" to R.string.finding_no_network_description,
            "cause_wifi_mobile_disconnected" to R.string.cause_wifi_mobile_disconnected,
            "cause_airplane_sim_apn" to R.string.cause_airplane_sim_apn,
            "finding_network_unknown_title" to R.string.finding_network_unknown_title,
            "finding_network_unknown_description" to R.string.finding_network_unknown_description,
            "finding_ip_unknown_title" to R.string.finding_ip_unknown_title,
            "finding_ip_unknown_description" to R.string.finding_ip_unknown_description,
            "finding_public_conflict_title" to R.string.finding_public_conflict_title,
            "finding_public_unknown_title" to R.string.finding_public_unknown_title,
            "finding_public_validated_conflict" to R.string.finding_public_validated_conflict,
            "finding_public_route_unavailable" to R.string.finding_public_route_unavailable,
            "finding_public_inconclusive" to R.string.finding_public_inconclusive,
            "cause_public_upstream_unavailable" to R.string.cause_public_upstream_unavailable,
            "cause_probe_policy" to R.string.cause_probe_policy,
            "finding_gateway_no_response_title" to R.string.finding_gateway_no_response_title,
            "finding_gateway_public_available" to R.string.finding_gateway_public_available,
            "finding_local_upstream_title" to R.string.finding_local_upstream_title,
            "finding_local_upstream_description" to R.string.finding_local_upstream_description,
            "cause_local_link" to R.string.cause_local_link,
            "cause_gateway_wan" to R.string.cause_gateway_wan,
            "cause_upstream_path" to R.string.cause_upstream_path,
            "diagnosis_normal_title" to R.string.diagnosis_normal_title,
            "finding_normal_description" to R.string.finding_normal_description,
            "finding_nxdomain_title" to R.string.finding_nxdomain_title,
            "finding_nxdomain_description" to R.string.finding_nxdomain_description,
            "finding_dns_public_available" to R.string.finding_dns_public_available,
            "finding_target_nxdomain_title" to R.string.finding_target_nxdomain_title,
            "finding_target_nxdomain_description" to R.string.finding_target_nxdomain_description,
            "finding_target_dns_failure" to R.string.finding_target_dns_failure,
            "finding_dns_failure_title" to R.string.finding_dns_failure_title,
            "cause_dns_path" to R.string.cause_dns_path,
            "cause_private_dns_vpn_proxy" to R.string.cause_private_dns_vpn_proxy,
            "finding_target_refused_title" to R.string.finding_target_refused_title,
            "finding_target_refused_description" to R.string.finding_target_refused_description,
            "finding_target_path_title" to R.string.finding_target_path_title,
            "finding_target_route_public_available" to R.string.finding_target_route_public_available,
            "finding_target_route_public_unknown" to R.string.finding_target_route_public_unknown,
            "cause_target_family_path" to R.string.cause_target_family_path,
            "cause_target_policy" to R.string.cause_target_policy,
            "finding_target_timeout_title" to R.string.finding_target_timeout_title,
            "finding_target_timeout_public_available" to R.string.finding_target_timeout_public_available,
            "finding_target_timeout_public_unknown" to R.string.finding_target_timeout_public_unknown,
            "cause_target_service_path" to R.string.cause_target_service_path,
            "cause_firewall_policy" to R.string.cause_firewall_policy,
            "finding_captive_title" to R.string.finding_captive_title,
            "finding_captive_description" to R.string.finding_captive_description,
            "finding_fake_ip_title" to R.string.finding_fake_ip_title,
            "finding_fake_ip_description" to R.string.finding_fake_ip_description,
            "finding_vpn_title" to R.string.finding_vpn_title,
            "finding_vpn_description" to R.string.finding_vpn_description,
            "diagnosis_normal_explanation" to R.string.diagnosis_normal_explanation,
            "diagnosis_no_network_title" to R.string.diagnosis_no_network_title,
            "diagnosis_no_network_explanation" to R.string.diagnosis_no_network_explanation,
            "diagnosis_limited_title" to R.string.diagnosis_limited_title,
            "diagnosis_captive_explanation" to R.string.diagnosis_captive_explanation,
            "diagnosis_public_unknown_explanation" to R.string.diagnosis_public_unknown_explanation,
            "diagnosis_attention_title" to R.string.diagnosis_attention_title,
            "diagnosis_unknown_title" to R.string.diagnosis_unknown_title,
            "diagnosis_conflicting_evidence" to R.string.diagnosis_conflicting_evidence,
            "diagnosis_insufficient_evidence" to R.string.diagnosis_insufficient_evidence,
            "recommendation_network_title" to R.string.recommendation_network_title,
            "recommendation_network_action" to R.string.recommendation_network_action,
            "recommendation_network_reason" to R.string.recommendation_network_reason,
            "recommendation_dns_retry_title" to R.string.recommendation_dns_retry_title,
            "recommendation_dns_retry_action" to R.string.recommendation_dns_retry_action,
            "recommendation_dns_retry_reason" to R.string.recommendation_dns_retry_reason,
            "recommendation_upstream_title" to R.string.recommendation_upstream_title,
            "recommendation_upstream_action" to R.string.recommendation_upstream_action,
            "recommendation_upstream_reason" to R.string.recommendation_upstream_reason,
            "recommendation_public_retry_action" to R.string.recommendation_public_retry_action,
            "recommendation_public_retry_reason" to R.string.recommendation_public_retry_reason,
            "recommendation_target_title" to R.string.recommendation_target_title,
            "recommendation_target_action" to R.string.recommendation_target_action,
            "recommendation_target_reason" to R.string.recommendation_target_reason,
            "recommendation_after_connect_action" to R.string.recommendation_after_connect_action,
            "recommendation_after_connect_reason" to R.string.recommendation_after_connect_reason,
            "recommendation_captive_title" to R.string.recommendation_captive_title,
            "recommendation_captive_action" to R.string.recommendation_captive_action,
            "recommendation_captive_reason" to R.string.recommendation_captive_reason,
            "recommendation_dns_environment_title" to R.string.recommendation_dns_environment_title,
            "recommendation_dns_environment_action" to R.string.recommendation_dns_environment_action,
            "recommendation_dns_environment_reason" to R.string.recommendation_dns_environment_reason,
            "recommendation_compare_title" to R.string.recommendation_compare_title,
            "recommendation_compare_action" to R.string.recommendation_compare_action,
            "recommendation_compare_reason" to R.string.recommendation_compare_reason,
            "recommendation_target_run_title" to R.string.recommendation_target_run_title,
            "recommendation_target_run_action" to R.string.recommendation_target_run_action,
            "recommendation_target_run_reason" to R.string.recommendation_target_run_reason,
        )
    }
}
